name: Publish to Crates.io

on:
  push:
    # 仅当推送以 'v' 开头的 tag 时触发 (例如 v0.1.0)
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish Cargo Crates
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hdc-rs
    steps:
      # 1. 检出代码
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        run: cargo test  --all-features

      - name: Publish to Crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
